Repository databrary/datavyu, pull requests merged in 2019-10, with the labels that each got.

#301 Fix reading user-entered FPS
  src/main/java/org/datavyu/views/VideoController.java
Labels: Type : bug, ui

#297 Update functions to interact with the Controller
  src/main/java/org/datavyu/views/VideoController.java
  src/main/resources/Datavyu_API.rb
Labels: ruby_api

#291 Embed JMenu Bar in JFrame on Mac OS
  src/main/java/org/datavyu/Datavyu.java
  src/main/java/org/datavyu/plugins/ffmpegplayer/FFmpegPlayer.java
  src/main/java/org/datavyu/plugins/ffmpegplayer/FFmpegStreamViewer.java
  src/main/java/org/datavyu/views/DatavyuView.java
  src/main/java/org/datavyu/views/VideoController.java
Labels: Platform : Mac, Player : ffmpeg, Type : bug, ui

#304 Integrate ffmpeg plugin 0.22 SNAPSHOT
  pom.xml
  src/main/java/org/datavyu/plugins/StreamViewer.java
  src/main/java/org/datavyu/plugins/ffmpegplayer/FFmpegPlayer.java
  src/main/java/org/datavyu/plugins/ffmpegplayer/FFmpegStreamViewer.java
  src/main/java/org/datavyu/plugins/mpv/MpvPlayer.java
  src/main/java/org/datavyu/plugins/mpv/MpvPlugin.java
  src/main/java/org/datavyu/plugins/mpv/MpvStreamViewer.java
  src/main/java/org/datavyu/plugins/nativeosx/AvFoundationPlayer.java
  src/main/java/org/datavyu/plugins/nativeosx/AvFoundationViewer.java
  src/main/java/org/datavyu/views/VideoController.java
Labels: Type : enhancement

#306 Map NativeOSXViewer (Datavyu 1.3.7) to AVFoundationViewer (DV 1.5.0+)
  src/main/java/org/datavyu/plugins/PluginManager.java
Labels: Type : bug

#308 Bump FFmpeg plugin version to 0.22
  pom.xml
Labels: Type : enhancement

#309 Release Datavyu 1.5.1-RC1
  pom.xml
  src/main/deploy/package/macosx/Info.plist
  src/main/deploy/package/windows/datavyu.iss
  src/main/resources/org/datavyu/resources/Datavyu.properties
Labels: Type : enhancement
