Repository databrary/datavyu, pull requests merged in 2019-03, with the labels that each got.

#187 Exclude MPV and NativeOSX from Mac and Win Platorms
  pom.xml
  src/main/java/org/datavyu/plugins/PluginManager.java
  src/main/java/org/datavyu/util/MacOS.java
Labels: enhancement

#160 Add Share Data Acknowledgment at first launch
  pom.xml
  src/main/java/org/datavyu/Datavyu.java
  src/main/java/org/datavyu/controllers/project/ProjectController.java
  src/main/java/org/datavyu/util/ConfigProperties.java
  src/main/java/org/datavyu/util/DatavyuVersion.java
  src/main/java/org/datavyu/views/DatavyuView.java
  src/main/java/org/datavyu/views/UpdateVersion.java
  src/main/resources/org/datavyu/views/resources/DatavyuView.properties
  src/main/resources/settings.xml
Labels: enhancement

#201 Prevent Jogging Out of Locked Region
  src/main/java/org/datavyu/plugins/ffmpegplayer/FFmpegStreamViewer.java
  src/main/java/org/datavyu/plugins/mpv/MpvStreamViewer.java
  src/main/java/org/datavyu/plugins/nativeosx/AvFoundationViewer.java
  src/main/java/org/datavyu/views/VideoController.java
Labels: bug

#200 Merge Periodic Sync and Fake playback
  src/main/java/org/datavyu/plugins/StreamViewerDialog.java
  src/main/java/org/datavyu/plugins/ffmpegplayer/FFmpegPlayer.java
  src/main/java/org/datavyu/util/ClockTimer.java
Labels: bug

#205 Add Seek to frame index feature for the FFmpeg plugin
  src/main/java/org/datavyu/plugins/StreamViewer.java
  src/main/java/org/datavyu/plugins/StreamViewerDialog.java
  src/main/java/org/datavyu/plugins/ffmpegplayer/FFmpegPlayer.java
  src/main/java/org/datavyu/plugins/ffmpegplayer/FFmpegStreamViewer.java
  src/main/java/org/datavyu/plugins/mpv/MpvStreamViewer.java
  src/main/java/org/datavyu/plugins/nativeosx/AvFoundationViewer.java
  src/main/java/org/datavyu/util/ClockTimer.java
  src/main/java/org/datavyu/views/VideoController.java
Labels: bug

#206 Update info.plist dependencies and Jar name
  src/main/deploy/package/macosx/Info.plist
Labels: bug, enhancement

#207 Clamp AVFoundation duration From first time frame to last one
  src/main/java/org/datavyu/plugins/nativeosx/AvFoundationPlayer.java
  src/main/java/org/datavyu/plugins/nativeosx/AvFoundationViewer.java
  src/main/java/org/datavyu/views/VideoController.java
Labels: bug

#209 Force update FPS when loading invalid Frame Rate
  src/main/java/org/datavyu/plugins/StreamViewerDialog.java
Labels: bug

#203 Feature api videos
  src/main/java/org/datavyu/plugins/PluginManager.java
  src/main/java/org/datavyu/views/VideoController.java
  src/main/resources/Datavyu_API.rb
Labels: enhancement, ruby_api

#211 Fix StreamViewer Clock listener methods
  src/main/java/org/datavyu/plugins/StreamViewer.java
  src/main/java/org/datavyu/plugins/StreamViewerDialog.java
  src/main/java/org/datavyu/plugins/ffmpegplayer/FFmpegStreamViewer.java
  src/main/java/org/datavyu/util/ClockTimer.java
  src/main/java/org/datavyu/views/VideoController.java
Labels: bug

#213 Bump version to 1.5.0 RC2
  compile_osx.sh
  compile_win.sh
  package-macos.sh
  pom.xml
  src/main/deploy/package/macosx/Info.plist
  src/main/resources/org/datavyu/resources/Datavyu.properties
Labels: enhancement
